name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Access GH_MOVIES_ACCESS_TOKEN
        env:
          GH_MOVIES_ACCESS_TOKEN: ${{ secrets.GH_MOVIES_ACCESS_TOKEN }}
          run: echo GH_MOVIES_ACCESS_TOKEN=\"$GH_MOVIES_ACCESS_TOKEN\" > ./local.properties
      - name: Build the app
        run: ./gradlew assembleDebug
